name: Zbuduj mObywatela
on: [workflow_dispatch]

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Pobierz kod
        uses: actions/checkout@v4

      - name: Ustaw wersje Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'

      - name: Kompilacja kodu do IPA
        run: |
          mkdir -p build
          # Wchodzimy do podfolderu App, gdzie faktycznie znajduje się projekt Xcode
          cd App
          xcodebuild -project App.xcodeproj -scheme "App" -configuration Release -sdk iphoneos CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO clean build
          
          # Pakowanie zbudowanej aplikacji do formatu IPA
          cd build/Release-iphoneos
          mkdir -p Payload
          cp -r App.app Payload/
          zip -r ../../../build/mObywatel.ipa Payload

      - name: Wypluj gotowy plik IPA
        uses: actions/upload-artifact@v4
        with:
          name: mObywatel-Gotowy-Plik
          path: build/mObywatel.ipa
